apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-76w8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xplf-tenant/status-quarkus-io/statusquarkusio-76w8@sha256:72035410493b85cc44f333303a61563268173a20582b54a6a41c789708a42d5e
        name: my-java-quarkus
        resources: {}
status: {}
